export const POKER_MESSAGE_HANDLER_MAP: Record<string, string> = {
  poker_join_table: 'handlePokerJoinTable',
  poker_leave_table: 'handlePokerLeaveTable',
  poker_add_chips: 'handlePokerAddChips',
  poker_action: 'handlePokerAction',
  poker_get_state: 'handlePokerGetState',
  poker_create_table: 'handlePokerCreateTable',
  poker_update_table_logo: 'handlePokerUpdateTableLogo',
  poker_quick_reaction: 'handlePokerQuickReaction',
  poker_avatar_emotion: 'handlePokerAvatarEmotion',
  poker_tournament_list: 'handlePokerTournamentList',
  poker_tournament_create: 'handlePokerTournamentCreate',
  poker_tournament_join: 'handlePokerTournamentJoin',
  poker_tournament_get_state: 'handlePokerTournamentGetState',
  poker_tournament_cancel: 'handlePokerTournamentCancel',
};
