export const TOURNAMENT_MESSAGE_HANDLER_MAP: Record<string, string> = {
  tournament_enter: 'handleTournamentEnter',
  tournament_leave: 'handleTournamentLeave',
  tournament_state: 'handleGetTournamentState',
  tournament_game_start: 'handleTournamentGameStart',
  tournament_player_action: 'handleTournamentPlayerAction',
  tournament_leaderboard: 'handleTournamentLeaderboard',
  tournament_leaderboard_by_id: 'handleTournamentLeaderboardById',
  tournament_info: 'handleGetTournamentInfo',
  tournament_create: 'handleTournamentCreate',
  create_freeroll: 'handleCreateFreeroll',
  tournament_list: 'handleTournamentList',
  tournament_join: 'handleTournamentJoin',
  tournament_unregister: 'handleTournamentUnregister',
  tournament_get_info: 'handleTournamentGetInfo',
  freeroll_list: 'handleFreerollList',
  freeroll_register: 'handleFreerollRegister',
  freeroll_join: 'handleFreerollJoin',
  tournament_entries_list: 'handleTournamentEntriesList',
  creator_tournaments: 'handleCreatorTournaments',
  creator_earnings: 'handleCreatorEarnings',
  tournament_cancel: 'handleTournamentCancel',
  tournament_reclaim: 'handleTournamentReclaim',
};
