/** 50 unique facts about poker — used by FactBot in multiplayer table chat. */
export const POKER_FACTS: string[] = [
  'Texas Hold\'em became the most popular poker variant worldwide after the early 2000s poker boom.',
  'In Hold\'em, each player gets 2 private cards and can use any combination with 5 community cards.',
  'The strongest possible hand in standard poker is a royal flush: A-K-Q-J-10 of the same suit.',
  'Pocket aces are the best starting hand in Hold\'em but still lose a significant percentage of the time.',
  'You can make a straight with an Ace as low (A-2-3-4-5) or high (10-J-Q-K-A).',
  'Position is one of the most important edges in poker because acting last gives maximum information.',
  'The button rotates clockwise each hand so every seat gets equal dealer position over time.',
  'Small blind and big blind force action so pots are contested every hand.',
  'A flush beats a straight, but a full house beats a flush.',
  'Four of a kind is also called "quads."',
  'A full house is often described verbally as "X full of Y" (for example, kings full of tens).',
  'In Hold\'em, you can use both hole cards, one hole card, or none of your hole cards at showdown.',
  'A board where all five cards are hearts means everyone has at least a heart flush available.',
  'If two players have the same hand rank, kickers determine the winner unless the board plays.',
  'When the board makes the best possible five-card hand for everyone, the pot is split.',
  'An "open-ended straight draw" has 8 outs, while a "gutshot" straight draw has 4 outs.',
  'A standard deck has 52 cards, creating 1,326 distinct two-card starting combos in Hold\'em.',
  'Pocket pairs appear about 5.9% of the time (roughly once every 17 hands).',
  'Suited starting hands occur about 23.5% of the time in Hold\'em.',
  'Unpaired unsuited hands are the most common starting hand category in Hold\'em.',
  'The term "the nuts" means the best possible hand at that moment.',
  'A "backdoor" draw needs runner-runner cards on turn and river to complete.',
  'Pot odds compare the current call amount to total pot size to guide profitable calls.',
  'Implied odds estimate future chips you can win when a draw completes.',
  'Fold equity is the value you gain when opponents may fold to your bet or raise.',
  'A continuation bet is a flop bet by the preflop aggressor, regardless of whether they improved.',
  'Check-raising can build pots and deny equity while disguising hand strength.',
  'Slow-playing is intentionally under-representing hand strength to induce bluffs.',
  'Bankroll management matters as much as strategy for surviving variance.',
  'Even top players experience long downswings due to poker variance.',
  'All-ins before the river involve luck because remaining community cards are unknown.',
  'A "bad beat" is when a strong favorite loses after all chips go in.',
  'A "cooler" is when two very strong hands collide and big chips go in naturally.',
  'Table image influences how often opponents call, fold, or bluff against you.',
  'Tight-aggressive (TAG) play is a common winning baseline strategy.',
  'Loose-aggressive (LAG) style applies pressure by playing more hands and betting often.',
  'HUD stats in online poker often track VPIP, PFR, and aggression frequency.',
  'In tournaments, stack depth is frequently measured in big blinds rather than chip count.',
  'In cash games, chips usually have direct monetary value and blinds stay constant.',
  'In tournaments, blinds increase over time to force action and finish the event.',
  'The "bubble" is the stage right before paid positions in a tournament.',
  'ICM (Independent Chip Model) changes correct strategy near payout jumps.',
  'A min-raise in no-limit Hold\'em is at least the size of the previous raise increment.',
  'String betting is not allowed in live poker; verbal declarations are often binding.',
  'Reading bet sizing tells can be as valuable as reading physical tells.',
  'Online poker removed many physical tells and increased focus on timing and sizing patterns.',
  'The World Series of Poker Main Event helped globalize poker through televised coverage.',
  'Short-handed tables usually play more aggressively than full-ring tables.',
  'Heads-up poker requires wider ranges and more frequent bluffing.',
  'In no-limit Hold\'em, one decision can put your entire stack at risk.',
];
