/** 50 unique facts about blackjack — used by FactBot in multiplayer chat. */
export const BLACKJACK_FACTS: string[] = [
  'Blackjack is also known as "21" and originated in French casinos around the 1700s under the name "Vingt-et-Un".',
  'The house edge in blackjack can be as low as 0.5% when using basic strategy — one of the lowest of any casino game.',
  'Card counting was popularized by Edward O. Thorp in his 1962 book "Beat the Dealer".',
  'The MIT Blackjack Team won millions from casinos throughout the 1980s and 1990s using team-based card counting.',
  'In a standard 6-deck shoe, there are 312 cards in play.',
  'The probability of getting a natural blackjack (Ace + 10-value card) is approximately 4.83%.',
  'Insurance is statistically one of the worst bets in blackjack — it carries a house edge of about 7.4%.',
  'The name "blackjack" comes from an early bonus payout for a hand of the Ace of Spades and a black Jack.',
  'Standing on 17 or higher is the foundation of basic strategy for players.',
  'The dealer must hit on 16 or below and stand on 17 or above in most casinos.',
  'Splitting Aces and 8s is considered the golden rule of blackjack strategy.',
  'Never split 10s or 5s — keeping 20 is almost always the best play, and two 5s make a strong 10 to double down on.',
  'A "soft" hand contains an Ace counted as 11, giving you flexibility to hit without busting.',
  'Blackjack has been played in some form for over 300 years.',
  'Napoleon Bonaparte was reportedly a fan of Vingt-et-Un and played it during his exile on Elba.',
  'The first card counting system, the Ten-Count, was developed by Edward Thorp using an IBM 704 computer.',
  'In a single deck game, the house edge can drop to around 0.17% with perfect basic strategy.',
  'The "shoe" — the device that holds multiple decks — was introduced to speed up dealing and combat card counting.',
  'Surrender is one of the most underused plays in blackjack; it saves money long-term in the right situations.',
  'The average blackjack hand is resolved in under 30 seconds in a live casino.',
  'Casinos make more money from blackjack than any other table game.',
  'Doubling down on 11 is one of the most profitable plays in blackjack.',
  'A blackjack (natural 21) typically pays 3:2, but some tables now pay only 6:5 — a significant disadvantage.',
  'In some European casinos, the dealer does not take a hole card until the player has acted — known as "European No Hole Card" rules.',
  'The probability of busting when hitting on 12 is about 31%, making it a borderline decision.',
  'Blackjack is the most popular casino card game in the world.',
  'Side bets like "Perfect Pairs" and "21+3" carry a much higher house edge than the main game.',
  'The concept of "wonging" — only joining a table when the count is favorable — is named after Stanford Wong.',
  'Continuous Shuffling Machines (CSMs) effectively eliminate card counting by shuffling after every hand.',
  'In Atlantic City, casinos are legally required to allow card counters to play — they cannot ban them.',
  'The Hi-Lo counting system assigns +1 to cards 2-6, 0 to 7-9, and -1 to 10-Ace.',
  'A "stiff hand" (12-16) is the most dangerous range — too low to stand confidently, too high to hit safely.',
  'Blackjack was the first casino game to be mathematically analyzed for optimal play.',
  'The average number of cards dealt per hand is approximately 2.7.',
  'In a fresh 52-card deck, the chance of the first card being an Ace is exactly 1 in 13 (7.69%).',
  'Ken Uston, a famous card counter, won a landmark court case in 1982 establishing that card counting is not cheating.',
  'Most basic strategy charts have around 270 different playing decisions.',
  'The "Martingale" betting system (doubling after losses) does not change the house edge — it only increases variance.',
  'A hand of 7-7-7 (three sevens) is considered one of the luckiest hands in blackjack folklore.',
  'In Spanish 21, all 10s are removed from the deck, significantly changing the odds.',
  'The term "bust" comes from the phrase "going bust," which originally meant going bankrupt.',
  'Professional blackjack players consider bankroll management more important than any single strategy decision.',
  'The chance of getting three blackjacks in a row from a 6-deck shoe is roughly 1 in 9,000.',
  'Some advantage players use "shuffle tracking" — following clumps of cards through a shuffle — instead of counting.',
  'The "rule of 45" suggests that when your hand and the dealer upcard total to about 9, the decision is very close.',
  'Blackjack tables typically have 5 to 7 betting spots for players.',
  'Ben Affleck was banned from playing blackjack at the Hard Rock Casino in Las Vegas for card counting.',
  'In Pontoon (the British version of blackjack), a five-card trick (5 cards under 21) beats everything except a natural.',
  'The first computer simulation of blackjack was run in 1956 by Roger Baldwin and his colleagues using desk calculators.',
  'Hole-carding — glimpsing the dealer\'s face-down card — is legal in most jurisdictions if the dealer accidentally exposes it.',
];
