/** Default 14 QuickChat phrases shown in the picker until the user edits. */
export const DEFAULT_QUICKCHAT_PHRASES: string[] = [
  'Hello!',
  'Good game!',
  'Nice hand',
  'Good luck',
  'Unlucky!',
  'Sorry',
  'HAHA!',
  'Wow',
  'WTF!',
  'I Won!',
  'You bluffed. right?',
  'Seriously?',
  'Thanks',
  'Well played.',
];

/** All QuickChat phrases by category for the Edit QuickChat modal. */
export const QUICKCHAT_PHRASES_BY_CATEGORY: Record<string, string[]> = {
  'Excitement / Hype': [
    "Let's go!",
    'Adrenaline rush',
    'Feeling it',
    'Hyped up',
    'Bring it on',
    'Fired up',
    'Game on',
    'Peak performance',
    'This is it',
    'My moment',
  ],
  'Frustration / Annoyance': [
    'Are you serious?',
    'Unbelievable',
    'Beyond tilted',
    'What even was that?',
    'My turn to lose',
    'Just stop it',
    'Rage quit incoming',
    'So annoying',
    "Can't catch a break",
    'Infuriating',
  ],
  'Sarcasm / Irony': [
    'So skilled',
    'Pure genius',
    'What a read',
    'Obviously',
    "Couldn't see that coming",
    'Shocking outcome',
    'Master strategist',
    "Beginner's luck",
    'Yeah, right',
    'Truly amazing',
  ],
  'Confidence / Swagger': [
    'I got this',
    'Easy game',
    'My table',
    'Fear me',
    'Predictable',
    'Too good',
    "You can't win",
    'Next level',
    'Bring a bigger stack',
    'Dominating',
  ],
  'Disbelief / Shock': [
    'No way!',
    'Speechless',
    'Utter madness',
    'Mind blown',
    'How is that possible?',
    'Wild hand',
    'What a rollercoaster',
    'Just wow',
    'Insane!',
    'Epic!',
  ],
  'Humor / Playfulness': [
    'LOL',
    'Gotcha!',
    'Oops!',
    'Whoops',
    'My bad',
    'Pure comedy',
    'Good times',
    'Just for fun',
    'Poker face engaged',
    'That was spicy',
  ],
  'Cynicism / Resignation': [
    'As expected',
    'Nothing new',
    'Classic poker',
    'Another day',
    'Seen it before',
    'Whatever happens',
    'Just dealing',
    'Zero surprise',
    'Always me',
    'So predictable',
  ],
  'Challenge / Taunting': [
    'Try harder',
    'Prove it',
    'Think you can?',
    'Show me',
    'Bring your best',
    'I dare you',
    "Who's next?",
    'Ready for more?',
    'You got guts',
    "Let's rumble",
  ],
  'Reflection / Observation': [
    'Interesting spot',
    'Deep thoughts',
    'What was that?',
    'Mind games',
    'Analyzing',
    'Pretty complex',
    'A lot to unpack',
    'Thinking face',
    'Learning curves',
    'Poker wisdom',
  ],
  'Blackjack': [
    '21!',
    'Blackjack!',
    'Busted again...',
    'Hit me!',
    'Stand pat.',
    'Double down!',
    'Insurance? No thanks.',
    'Split it!',
    'Push...',
    'Dealer bust!',
    'Natural!',
    'Five-card Charlie!',
  ],
  'Leaving / Signing Off': [
    'See ya',
    'Later, losers',
    "I'm out",
    'Peace!',
    'Next time',
    'Time to bounce',
    'Catch you later',
    'Done for now',
    'Adios',
    'Until then',
  ],
};

/** Default QuickChat phrases for multiplayer blackjack — blackjack flavour mixed with general. */
export const DEFAULT_BLACKJACK_QUICKCHAT_PHRASES: string[] = [
  '21!',
  'Blackjack!',
  'Busted again...',
  'Hit me!',
  'Stand pat.',
  'Double down!',
  'Insurance? No thanks.',
  'Nice hand',
  'Good luck',
  'Unlucky!',
  'HAHA!',
  'Good game!',
  'Wow',
  'Thanks',
];

/** Flat list of all phrases (for quick lookup / dedupe). */
export const ALL_QUICKCHAT_PHRASES: string[] = Object.values(
  QUICKCHAT_PHRASES_BY_CATEGORY,
).flat();
