import { MemeTemplate } from './types';

// Using api.memegen.link for reliable, CORS-friendly meme templates
const BASE_URL = 'https://api.memegen.link/images';

export const MEME_TEMPLATES: MemeTemplate[] = [
  { id: 'fry', name: 'Futurama Fry', url: `${BASE_URL}/fry.png`, width: 600, height: 400 },
  { id: 'doge', name: 'Doge', url: `${BASE_URL}/doge.png`, width: 600, height: 600 },
  { id: 'success', name: 'Success Kid', url: `${BASE_URL}/success.png`, width: 500, height: 500 },
  { id: 'wonka', name: 'Condescending Wonka', url: `${BASE_URL}/wonka.png`, width: 550, height: 545 },
  { id: 'disastergirl', name: 'Disaster Girl', url: `${BASE_URL}/disastergirl.png`, width: 500, height: 375 },
  { id: 'toy', name: 'Toy Story Everywhere', url: `${BASE_URL}/toy.png`, width: 500, height: 305 },
  { id: 'spongebob', name: 'Mocking Spongebob', url: `${BASE_URL}/spongebob.png`, width: 500, height: 353 },
  { id: 'pigeon', name: 'Is This a Pigeon?', url: `${BASE_URL}/pigeon.png`, width: 600, height: 408 },
  { id: 'drake', name: 'Drake Hotline Bling', url: `${BASE_URL}/drake.png`, width: 600, height: 600 },
  { id: 'woman-yelling', name: 'Woman Yelling at Cat', url: `${BASE_URL}/woman-yelling.png`, width: 600, height: 400 },
  { id: 'fine', name: 'This is Fine', url: `${BASE_URL}/fine.png`, width: 580, height: 282 },
  { id: 'bad', name: 'X is Bad and You Should Feel Bad', url: `${BASE_URL}/bad.png`, width: 500, height: 375 },
  { id: 'aag', name: 'Ancient Aliens Guy', url: `${BASE_URL}/aag.png`, width: 500, height: 437 },
  { id: 'oprah', name: 'Oprah You Get A...', url: `${BASE_URL}/oprah.png`, width: 600, height: 396 },
  { id: 'philosoraptor', name: 'Philosoraptor', url: `${BASE_URL}/philosoraptor.png`, width: 500, height: 500 },
  { id: 'patrick', name: 'Push It Somewhere Else Patrick', url: `${BASE_URL}/patrick.png`, width: 600, height: 400 },
  { id: 'awkward', name: 'Awkward Penguin', url: `${BASE_URL}/awkward.png`, width: 500, height: 500 },
  { id: 'blb', name: 'Bad Luck Brian', url: `${BASE_URL}/blb.png`, width: 500, height: 500 },
  { id: 'kermit', name: 'But That\'s None of My Business', url: `${BASE_URL}/kermit.png`, width: 600, height: 600 },
  { id: 'mordor', name: 'One Does Not Simply', url: `${BASE_URL}/mordor.png`, width: 550, height: 335 },
  { id: 'buzz', name: 'X, X Everywhere', url: `${BASE_URL}/buzz.png`, width: 600, height: 400 },
  { id: 'firstworld', name: 'First World Problems', url: `${BASE_URL}/firstworld.png`, width: 550, height: 549 },
  { id: 'sad-biden', name: 'Sad Joe Biden', url: `${BASE_URL}/sad-biden.png`, width: 500, height: 500 },
  { id: 'rollsafe', name: 'Roll Safe Think About It', url: `${BASE_URL}/rollsafe.png`, width: 600, height: 338 },
  { id: 'confession', name: 'Confession Bear', url: `${BASE_URL}/confession.png`, width: 500, height: 500 },
  { id: 'interesting', name: 'Most Interesting Man', url: `${BASE_URL}/interesting.png`, width: 550, height: 550 },
  { id: 'grumpycat', name: 'Grumpy Cat', url: `${BASE_URL}/grumpycat.png`, width: 500, height: 617 },
  { id: 'waiting', name: 'Waiting Skeleton', url: `${BASE_URL}/waiting.png`, width: 600, height: 400 },
  { id: 'yodawg', name: 'Yo Dawg', url: `${BASE_URL}/yodawg.png`, width: 500, height: 323 },
  { id: 'spiderman', name: 'Spiderman Pointing', url: `${BASE_URL}/spiderman.png`, width: 600, height: 450 },
  { id: 'afraid', name: 'Afraid to Ask Andy', url: `${BASE_URL}/afraid.png`, width: 600, height: 400 },
  { id: 'ants', name: 'Do You Want Ants?', url: `${BASE_URL}/ants.png`, width: 600, height: 400 },
  { id: 'boat', name: 'I Should Buy a Boat', url: `${BASE_URL}/boat.png`, width: 500, height: 500 },
  { id: 'both', name: 'Why Not Both?', url: `${BASE_URL}/both.png`, width: 500, height: 500 },
  { id: 'bs', name: 'Bernie Sanders Asking', url: `${BASE_URL}/bs.png`, width: 600, height: 600 },
  { id: 'cmm', name: 'Change My Mind', url: `${BASE_URL}/cmm.png`, width: 600, height: 600 },
  { id: 'db', name: 'Distracted Boyfriend', url: `${BASE_URL}/db.png`, width: 800, height: 600 },
  { id: 'ds', name: 'Daily Struggle', url: `${BASE_URL}/ds.png`, width: 600, height: 600 },
  { id: 'exit', name: 'Left Exit 12 Off Ramp', url: `${BASE_URL}/exit.png`, width: 800, height: 600 },
  { id: 'facepalm', name: 'Picard Facepalm', url: `${BASE_URL}/facepalm.png`, width: 600, height: 400 },
  { id: 'fbf', name: 'Foul Bachelor Frog', url: `${BASE_URL}/fbf.png`, width: 600, height: 600 },
  { id: 'gears', name: 'Grinds My Gears', url: `${BASE_URL}/gears.png`, width: 600, height: 400 },
  { id: 'ggg', name: 'Good Guy Greg', url: `${BASE_URL}/ggg.png`, width: 600, height: 600 },
  { id: 'hagrid', name: 'I Shouldn\'t Have Said That', url: `${BASE_URL}/hagrid.png`, width: 600, height: 600 },
  { id: 'inigo', name: 'You Keep Using That Word', url: `${BASE_URL}/inigo.png`, width: 600, height: 400 },
  { id: 'iw', name: 'Insanity Wolf', url: `${BASE_URL}/iw.png`, width: 600, height: 600 },
  { id: 'joker', name: 'Joker Mind Loss', url: `${BASE_URL}/joker.png`, width: 600, height: 400 },
  { id: 'leo', name: 'Leonardo DiCaprio Cheers', url: `${BASE_URL}/leo.png`, width: 600, height: 400 },
  { id: 'matrix', name: 'Matrix Morpheus', url: `${BASE_URL}/matrix.png`, width: 600, height: 400 },
  { id: 'money', name: 'Shut Up and Take My Money', url: `${BASE_URL}/money.png`, width: 600, height: 400 },
  { id: 'nice', name: 'So I Got That Goin\' For Me', url: `${BASE_URL}/nice.png`, width: 600, height: 400 },
  { id: 'noidea', name: 'I Have No Idea What I\'m Doing', url: `${BASE_URL}/noidea.png`, width: 600, height: 400 },
  { id: 'oag', name: 'Overly Attached Girlfriend', url: `${BASE_URL}/oag.png`, width: 600, height: 600 },
  { id: 'remembers', name: 'Pepperidge Farm Remembers', url: `${BASE_URL}/remembers.png`, width: 600, height: 400 },
  { id: 'saltbae', name: 'Salt Bae', url: `${BASE_URL}/saltbae.png`, width: 600, height: 600 },
  { id: 'scumbag', name: 'Scumbag Steve', url: `${BASE_URL}/scumbag.png`, width: 600, height: 600 },
  { id: 'stonks', name: 'Stonks', url: `${BASE_URL}/stonks.png`, width: 600, height: 450 },
  { id: 'toohigh', name: 'The Rent Is Too Damn High', url: `${BASE_URL}/toohigh.png`, width: 600, height: 400 },
  { id: 'xy', name: 'X all the Y', url: `${BASE_URL}/xy.png`, width: 600, height: 400 },
  { id: 'yuno', name: 'Y U NO', url: `${BASE_URL}/yuno.png`, width: 600, height: 400 },
];