export const morbiusTournamentAbi = [
  {
    inputs: [
      { name: 'buyInAmount', type: 'uint256' },
      { name: 'maxPlayers', type: 'uint256' },
      { name: 'prizeToken', type: 'address' },
      { name: 'prizeAmount', type: 'uint256' },
    ],
    name: 'createTournament',
    outputs: [{ name: 'tournamentId', type: 'uint256' }],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [{ name: 'tournamentId', type: 'uint256' }],
    name: 'joinTournament',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [{ name: 'tournamentId', type: 'uint256' }],
    name: 'getTournament',
    outputs: [
      { name: 'creator', type: 'address' },
      { name: 'buyInAmount', type: 'uint256' },
      { name: 'maxPlayers', type: 'uint256' },
      { name: 'prizeToken', type: 'address' },
      { name: 'prizeAmount', type: 'uint256' },
      { name: 'prizePool', type: 'uint256' },
      { name: 'entryCount', type: 'uint256' },
      { name: 'status', type: 'uint8' },
      { name: 'createdAt', type: 'uint256' },
    ],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [],
    name: 'getTournamentCount',
    outputs: [{ name: '', type: 'uint256' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [
      { name: 'tournamentId', type: 'uint256' },
      { name: 'player', type: 'address' },
    ],
    name: 'hasJoined',
    outputs: [{ name: '', type: 'bool' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    anonymous: false,
    inputs: [
      { indexed: true, name: 'tournamentId', type: 'uint256' },
      { indexed: true, name: 'creator', type: 'address' },
      { indexed: false, name: 'buyInAmount', type: 'uint256' },
      { indexed: false, name: 'maxPlayers', type: 'uint256' },
      { indexed: false, name: 'prizeToken', type: 'address' },
      { indexed: false, name: 'prizeAmount', type: 'uint256' },
    ],
    name: 'TournamentCreated',
    type: 'event',
  },
] as const;
